// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.1
// source: sdk/plugin/proto/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginLifecycle_GetInfo_FullMethodName        = "/weknora.plugin.v1.PluginLifecycle/GetInfo"
	PluginLifecycle_HealthCheck_FullMethodName    = "/weknora.plugin.v1.PluginLifecycle/HealthCheck"
	PluginLifecycle_ValidateConfig_FullMethodName = "/weknora.plugin.v1.PluginLifecycle/ValidateConfig"
	PluginLifecycle_Shutdown_FullMethodName       = "/weknora.plugin.v1.PluginLifecycle/Shutdown"
)

// PluginLifecycleClient is the client API for PluginLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginLifecycleClient interface {
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*PluginInfo, error)
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error)
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type pluginLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginLifecycleClient(cc grpc.ClientConnInterface) PluginLifecycleClient {
	return &pluginLifecycleClient{cc}
}

func (c *pluginLifecycleClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, PluginLifecycle_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) ValidateConfig(ctx context.Context, in *ValidateConfigRequest, opts ...grpc.CallOption) (*ValidateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateConfigResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_ValidateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginLifecycleClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, PluginLifecycle_Shutdown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginLifecycleServer is the server API for PluginLifecycle service.
// All implementations must embed UnimplementedPluginLifecycleServer
// for forward compatibility.
type PluginLifecycleServer interface {
	GetInfo(context.Context, *GetInfoRequest) (*PluginInfo, error)
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error)
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
	mustEmbedUnimplementedPluginLifecycleServer()
}

// UnimplementedPluginLifecycleServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginLifecycleServer struct{}

func (UnimplementedPluginLifecycleServer) GetInfo(context.Context, *GetInfoRequest) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedPluginLifecycleServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedPluginLifecycleServer) ValidateConfig(context.Context, *ValidateConfigRequest) (*ValidateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateConfig not implemented")
}
func (UnimplementedPluginLifecycleServer) Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Shutdown not implemented")
}
func (UnimplementedPluginLifecycleServer) mustEmbedUnimplementedPluginLifecycleServer() {}
func (UnimplementedPluginLifecycleServer) testEmbeddedByValue()                         {}

// UnsafePluginLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginLifecycleServer will
// result in compilation errors.
type UnsafePluginLifecycleServer interface {
	mustEmbedUnimplementedPluginLifecycleServer()
}

func RegisterPluginLifecycleServer(s grpc.ServiceRegistrar, srv PluginLifecycleServer) {
	// If the following call panics, it indicates UnimplementedPluginLifecycleServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginLifecycle_ServiceDesc, srv)
}

func _PluginLifecycle_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_ValidateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).ValidateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_ValidateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).ValidateConfig(ctx, req.(*ValidateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginLifecycle_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginLifecycleServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginLifecycle_Shutdown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginLifecycleServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginLifecycle_ServiceDesc is the grpc.ServiceDesc for PluginLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.PluginLifecycle",
	HandlerType: (*PluginLifecycleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _PluginLifecycle_GetInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _PluginLifecycle_HealthCheck_Handler,
		},
		{
			MethodName: "ValidateConfig",
			Handler:    _PluginLifecycle_ValidateConfig_Handler,
		},
		{
			MethodName: "Shutdown",
			Handler:    _PluginLifecycle_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/plugin/proto/plugin.proto",
}

const (
	DocumentParserPlugin_Describe_FullMethodName = "/weknora.plugin.v1.DocumentParserPlugin/Describe"
	DocumentParserPlugin_Parse_FullMethodName    = "/weknora.plugin.v1.DocumentParserPlugin/Parse"
)

// DocumentParserPluginClient is the client API for DocumentParserPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentParserPluginClient interface {
	Describe(ctx context.Context, in *DocumentParserDescribeRequest, opts ...grpc.CallOption) (*DocumentParserDescribeResponse, error)
	Parse(ctx context.Context, in *DocumentParserParseRequest, opts ...grpc.CallOption) (*DocumentParserParseResponse, error)
}

type documentParserPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentParserPluginClient(cc grpc.ClientConnInterface) DocumentParserPluginClient {
	return &documentParserPluginClient{cc}
}

func (c *documentParserPluginClient) Describe(ctx context.Context, in *DocumentParserDescribeRequest, opts ...grpc.CallOption) (*DocumentParserDescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentParserDescribeResponse)
	err := c.cc.Invoke(ctx, DocumentParserPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentParserPluginClient) Parse(ctx context.Context, in *DocumentParserParseRequest, opts ...grpc.CallOption) (*DocumentParserParseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DocumentParserParseResponse)
	err := c.cc.Invoke(ctx, DocumentParserPlugin_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentParserPluginServer is the server API for DocumentParserPlugin service.
// All implementations must embed UnimplementedDocumentParserPluginServer
// for forward compatibility.
type DocumentParserPluginServer interface {
	Describe(context.Context, *DocumentParserDescribeRequest) (*DocumentParserDescribeResponse, error)
	Parse(context.Context, *DocumentParserParseRequest) (*DocumentParserParseResponse, error)
	mustEmbedUnimplementedDocumentParserPluginServer()
}

// UnimplementedDocumentParserPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentParserPluginServer struct{}

func (UnimplementedDocumentParserPluginServer) Describe(context.Context, *DocumentParserDescribeRequest) (*DocumentParserDescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedDocumentParserPluginServer) Parse(context.Context, *DocumentParserParseRequest) (*DocumentParserParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedDocumentParserPluginServer) mustEmbedUnimplementedDocumentParserPluginServer() {}
func (UnimplementedDocumentParserPluginServer) testEmbeddedByValue()                              {}

// UnsafeDocumentParserPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentParserPluginServer will
// result in compilation errors.
type UnsafeDocumentParserPluginServer interface {
	mustEmbedUnimplementedDocumentParserPluginServer()
}

func RegisterDocumentParserPluginServer(s grpc.ServiceRegistrar, srv DocumentParserPluginServer) {
	// If the following call panics, it indicates UnimplementedDocumentParserPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentParserPlugin_ServiceDesc, srv)
}

func _DocumentParserPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentParserDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentParserPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentParserPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentParserPluginServer).Describe(ctx, req.(*DocumentParserDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentParserPlugin_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentParserParseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentParserPluginServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentParserPlugin_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentParserPluginServer).Parse(ctx, req.(*DocumentParserParseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentParserPlugin_ServiceDesc is the grpc.ServiceDesc for DocumentParserPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentParserPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DocumentParserPlugin",
	HandlerType: (*DocumentParserPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _DocumentParserPlugin_Describe_Handler,
		},
		{
			MethodName: "Parse",
			Handler:    _DocumentParserPlugin_Parse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/plugin/proto/plugin.proto",
}

const (
	WebSearchPlugin_Describe_FullMethodName = "/weknora.plugin.v1.WebSearchPlugin/Describe"
	WebSearchPlugin_Search_FullMethodName   = "/weknora.plugin.v1.WebSearchPlugin/Search"
)

// WebSearchPluginClient is the client API for WebSearchPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebSearchPluginClient interface {
	Describe(ctx context.Context, in *WebSearchDescribeRequest, opts ...grpc.CallOption) (*WebSearchDescribeResponse, error)
	Search(ctx context.Context, in *WebSearchRequest, opts ...grpc.CallOption) (*WebSearchResponse, error)
}

type webSearchPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewWebSearchPluginClient(cc grpc.ClientConnInterface) WebSearchPluginClient {
	return &webSearchPluginClient{cc}
}

func (c *webSearchPluginClient) Describe(ctx context.Context, in *WebSearchDescribeRequest, opts ...grpc.CallOption) (*WebSearchDescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebSearchDescribeResponse)
	err := c.cc.Invoke(ctx, WebSearchPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *webSearchPluginClient) Search(ctx context.Context, in *WebSearchRequest, opts ...grpc.CallOption) (*WebSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebSearchResponse)
	err := c.cc.Invoke(ctx, WebSearchPlugin_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebSearchPluginServer is the server API for WebSearchPlugin service.
// All implementations must embed UnimplementedWebSearchPluginServer
// for forward compatibility.
type WebSearchPluginServer interface {
	Describe(context.Context, *WebSearchDescribeRequest) (*WebSearchDescribeResponse, error)
	Search(context.Context, *WebSearchRequest) (*WebSearchResponse, error)
	mustEmbedUnimplementedWebSearchPluginServer()
}

// UnimplementedWebSearchPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebSearchPluginServer struct{}

func (UnimplementedWebSearchPluginServer) Describe(context.Context, *WebSearchDescribeRequest) (*WebSearchDescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedWebSearchPluginServer) Search(context.Context, *WebSearchRequest) (*WebSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedWebSearchPluginServer) mustEmbedUnimplementedWebSearchPluginServer() {}
func (UnimplementedWebSearchPluginServer) testEmbeddedByValue()                         {}

// UnsafeWebSearchPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebSearchPluginServer will
// result in compilation errors.
type UnsafeWebSearchPluginServer interface {
	mustEmbedUnimplementedWebSearchPluginServer()
}

func RegisterWebSearchPluginServer(s grpc.ServiceRegistrar, srv WebSearchPluginServer) {
	// If the following call panics, it indicates UnimplementedWebSearchPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebSearchPlugin_ServiceDesc, srv)
}

func _WebSearchPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebSearchDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSearchPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSearchPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSearchPluginServer).Describe(ctx, req.(*WebSearchDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WebSearchPlugin_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WebSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebSearchPluginServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebSearchPlugin_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebSearchPluginServer).Search(ctx, req.(*WebSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WebSearchPlugin_ServiceDesc is the grpc.ServiceDesc for WebSearchPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebSearchPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.WebSearchPlugin",
	HandlerType: (*WebSearchPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _WebSearchPlugin_Describe_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _WebSearchPlugin_Search_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/plugin/proto/plugin.proto",
}

const (
	ModelProviderPlugin_Describe_FullMethodName   = "/weknora.plugin.v1.ModelProviderPlugin/Describe"
	ModelProviderPlugin_ListModels_FullMethodName = "/weknora.plugin.v1.ModelProviderPlugin/ListModels"
)

// ModelProviderPluginClient is the client API for ModelProviderPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModelProviderPluginClient interface {
	Describe(ctx context.Context, in *ModelProviderDescribeRequest, opts ...grpc.CallOption) (*ModelProviderDescribeResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
}

type modelProviderPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewModelProviderPluginClient(cc grpc.ClientConnInterface) ModelProviderPluginClient {
	return &modelProviderPluginClient{cc}
}

func (c *modelProviderPluginClient) Describe(ctx context.Context, in *ModelProviderDescribeRequest, opts ...grpc.CallOption) (*ModelProviderDescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModelProviderDescribeResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *modelProviderPluginClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, ModelProviderPlugin_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModelProviderPluginServer is the server API for ModelProviderPlugin service.
// All implementations must embed UnimplementedModelProviderPluginServer
// for forward compatibility.
type ModelProviderPluginServer interface {
	Describe(context.Context, *ModelProviderDescribeRequest) (*ModelProviderDescribeResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	mustEmbedUnimplementedModelProviderPluginServer()
}

// UnimplementedModelProviderPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModelProviderPluginServer struct{}

func (UnimplementedModelProviderPluginServer) Describe(context.Context, *ModelProviderDescribeRequest) (*ModelProviderDescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedModelProviderPluginServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedModelProviderPluginServer) mustEmbedUnimplementedModelProviderPluginServer() {}
func (UnimplementedModelProviderPluginServer) testEmbeddedByValue()                             {}

// UnsafeModelProviderPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModelProviderPluginServer will
// result in compilation errors.
type UnsafeModelProviderPluginServer interface {
	mustEmbedUnimplementedModelProviderPluginServer()
}

func RegisterModelProviderPluginServer(s grpc.ServiceRegistrar, srv ModelProviderPluginServer) {
	// If the following call panics, it indicates UnimplementedModelProviderPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ModelProviderPlugin_ServiceDesc, srv)
}

func _ModelProviderPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModelProviderDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).Describe(ctx, req.(*ModelProviderDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ModelProviderPlugin_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModelProviderPluginServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ModelProviderPlugin_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModelProviderPluginServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ModelProviderPlugin_ServiceDesc is the grpc.ServiceDesc for ModelProviderPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ModelProviderPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.ModelProviderPlugin",
	HandlerType: (*ModelProviderPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _ModelProviderPlugin_Describe_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _ModelProviderPlugin_ListModels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/plugin/proto/plugin.proto",
}

const (
	RetrieverPlugin_Describe_FullMethodName                 = "/weknora.plugin.v1.RetrieverPlugin/Describe"
	RetrieverPlugin_Retrieve_FullMethodName                 = "/weknora.plugin.v1.RetrieverPlugin/Retrieve"
	RetrieverPlugin_SaveIndex_FullMethodName                = "/weknora.plugin.v1.RetrieverPlugin/SaveIndex"
	RetrieverPlugin_BatchSaveIndex_FullMethodName           = "/weknora.plugin.v1.RetrieverPlugin/BatchSaveIndex"
	RetrieverPlugin_DeleteByChunkIDs_FullMethodName         = "/weknora.plugin.v1.RetrieverPlugin/DeleteByChunkIDs"
	RetrieverPlugin_DeleteBySourceIDs_FullMethodName        = "/weknora.plugin.v1.RetrieverPlugin/DeleteBySourceIDs"
	RetrieverPlugin_DeleteByKnowledgeIDs_FullMethodName     = "/weknora.plugin.v1.RetrieverPlugin/DeleteByKnowledgeIDs"
	RetrieverPlugin_CopyIndices_FullMethodName              = "/weknora.plugin.v1.RetrieverPlugin/CopyIndices"
	RetrieverPlugin_UpdateChunkEnabledStatus_FullMethodName = "/weknora.plugin.v1.RetrieverPlugin/UpdateChunkEnabledStatus"
	RetrieverPlugin_UpdateChunkTagID_FullMethodName         = "/weknora.plugin.v1.RetrieverPlugin/UpdateChunkTagID"
)

// RetrieverPluginClient is the client API for RetrieverPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RetrieverPluginClient interface {
	Describe(ctx context.Context, in *RetrieverDescribeRequest, opts ...grpc.CallOption) (*RetrieverDescribeResponse, error)
	Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error)
	SaveIndex(ctx context.Context, in *SaveIndexRequest, opts ...grpc.CallOption) (*SaveIndexResponse, error)
	BatchSaveIndex(ctx context.Context, in *BatchSaveIndexRequest, opts ...grpc.CallOption) (*BatchSaveIndexResponse, error)
	DeleteByChunkIDs(ctx context.Context, in *DeleteByChunkIDsRequest, opts ...grpc.CallOption) (*DeleteByChunkIDsResponse, error)
	DeleteBySourceIDs(ctx context.Context, in *DeleteBySourceIDsRequest, opts ...grpc.CallOption) (*DeleteBySourceIDsResponse, error)
	DeleteByKnowledgeIDs(ctx context.Context, in *DeleteByKnowledgeIDsRequest, opts ...grpc.CallOption) (*DeleteByKnowledgeIDsResponse, error)
	CopyIndices(ctx context.Context, in *CopyIndicesRequest, opts ...grpc.CallOption) (*CopyIndicesResponse, error)
	UpdateChunkEnabledStatus(ctx context.Context, in *UpdateChunkEnabledStatusRequest, opts ...grpc.CallOption) (*UpdateChunkEnabledStatusResponse, error)
	UpdateChunkTagID(ctx context.Context, in *UpdateChunkTagIDRequest, opts ...grpc.CallOption) (*UpdateChunkTagIDResponse, error)
}

type retrieverPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewRetrieverPluginClient(cc grpc.ClientConnInterface) RetrieverPluginClient {
	return &retrieverPluginClient{cc}
}

func (c *retrieverPluginClient) Describe(ctx context.Context, in *RetrieverDescribeRequest, opts ...grpc.CallOption) (*RetrieverDescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieverDescribeResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) Retrieve(ctx context.Context, in *RetrieveRequest, opts ...grpc.CallOption) (*RetrieveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetrieveResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_Retrieve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) SaveIndex(ctx context.Context, in *SaveIndexRequest, opts ...grpc.CallOption) (*SaveIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveIndexResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_SaveIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) BatchSaveIndex(ctx context.Context, in *BatchSaveIndexRequest, opts ...grpc.CallOption) (*BatchSaveIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchSaveIndexResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_BatchSaveIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) DeleteByChunkIDs(ctx context.Context, in *DeleteByChunkIDsRequest, opts ...grpc.CallOption) (*DeleteByChunkIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByChunkIDsResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_DeleteByChunkIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) DeleteBySourceIDs(ctx context.Context, in *DeleteBySourceIDsRequest, opts ...grpc.CallOption) (*DeleteBySourceIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBySourceIDsResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_DeleteBySourceIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) DeleteByKnowledgeIDs(ctx context.Context, in *DeleteByKnowledgeIDsRequest, opts ...grpc.CallOption) (*DeleteByKnowledgeIDsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteByKnowledgeIDsResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_DeleteByKnowledgeIDs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) CopyIndices(ctx context.Context, in *CopyIndicesRequest, opts ...grpc.CallOption) (*CopyIndicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyIndicesResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_CopyIndices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) UpdateChunkEnabledStatus(ctx context.Context, in *UpdateChunkEnabledStatusRequest, opts ...grpc.CallOption) (*UpdateChunkEnabledStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateChunkEnabledStatusResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_UpdateChunkEnabledStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *retrieverPluginClient) UpdateChunkTagID(ctx context.Context, in *UpdateChunkTagIDRequest, opts ...grpc.CallOption) (*UpdateChunkTagIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateChunkTagIDResponse)
	err := c.cc.Invoke(ctx, RetrieverPlugin_UpdateChunkTagID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrieverPluginServer is the server API for RetrieverPlugin service.
// All implementations must embed UnimplementedRetrieverPluginServer
// for forward compatibility.
type RetrieverPluginServer interface {
	Describe(context.Context, *RetrieverDescribeRequest) (*RetrieverDescribeResponse, error)
	Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error)
	SaveIndex(context.Context, *SaveIndexRequest) (*SaveIndexResponse, error)
	BatchSaveIndex(context.Context, *BatchSaveIndexRequest) (*BatchSaveIndexResponse, error)
	DeleteByChunkIDs(context.Context, *DeleteByChunkIDsRequest) (*DeleteByChunkIDsResponse, error)
	DeleteBySourceIDs(context.Context, *DeleteBySourceIDsRequest) (*DeleteBySourceIDsResponse, error)
	DeleteByKnowledgeIDs(context.Context, *DeleteByKnowledgeIDsRequest) (*DeleteByKnowledgeIDsResponse, error)
	CopyIndices(context.Context, *CopyIndicesRequest) (*CopyIndicesResponse, error)
	UpdateChunkEnabledStatus(context.Context, *UpdateChunkEnabledStatusRequest) (*UpdateChunkEnabledStatusResponse, error)
	UpdateChunkTagID(context.Context, *UpdateChunkTagIDRequest) (*UpdateChunkTagIDResponse, error)
	mustEmbedUnimplementedRetrieverPluginServer()
}

// UnimplementedRetrieverPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRetrieverPluginServer struct{}

func (UnimplementedRetrieverPluginServer) Describe(context.Context, *RetrieverDescribeRequest) (*RetrieverDescribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedRetrieverPluginServer) Retrieve(context.Context, *RetrieveRequest) (*RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Retrieve not implemented")
}
func (UnimplementedRetrieverPluginServer) SaveIndex(context.Context, *SaveIndexRequest) (*SaveIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveIndex not implemented")
}
func (UnimplementedRetrieverPluginServer) BatchSaveIndex(context.Context, *BatchSaveIndexRequest) (*BatchSaveIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchSaveIndex not implemented")
}
func (UnimplementedRetrieverPluginServer) DeleteByChunkIDs(context.Context, *DeleteByChunkIDsRequest) (*DeleteByChunkIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByChunkIDs not implemented")
}
func (UnimplementedRetrieverPluginServer) DeleteBySourceIDs(context.Context, *DeleteBySourceIDsRequest) (*DeleteBySourceIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBySourceIDs not implemented")
}
func (UnimplementedRetrieverPluginServer) DeleteByKnowledgeIDs(context.Context, *DeleteByKnowledgeIDsRequest) (*DeleteByKnowledgeIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteByKnowledgeIDs not implemented")
}
func (UnimplementedRetrieverPluginServer) CopyIndices(context.Context, *CopyIndicesRequest) (*CopyIndicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CopyIndices not implemented")
}
func (UnimplementedRetrieverPluginServer) UpdateChunkEnabledStatus(context.Context, *UpdateChunkEnabledStatusRequest) (*UpdateChunkEnabledStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChunkEnabledStatus not implemented")
}
func (UnimplementedRetrieverPluginServer) UpdateChunkTagID(context.Context, *UpdateChunkTagIDRequest) (*UpdateChunkTagIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChunkTagID not implemented")
}
func (UnimplementedRetrieverPluginServer) mustEmbedUnimplementedRetrieverPluginServer() {}
func (UnimplementedRetrieverPluginServer) testEmbeddedByValue()                         {}

// UnsafeRetrieverPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RetrieverPluginServer will
// result in compilation errors.
type UnsafeRetrieverPluginServer interface {
	mustEmbedUnimplementedRetrieverPluginServer()
}

func RegisterRetrieverPluginServer(s grpc.ServiceRegistrar, srv RetrieverPluginServer) {
	// If the following call panics, it indicates UnimplementedRetrieverPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RetrieverPlugin_ServiceDesc, srv)
}

func _RetrieverPlugin_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieverDescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).Describe(ctx, req.(*RetrieverDescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_Retrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).Retrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_Retrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).Retrieve(ctx, req.(*RetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_SaveIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).SaveIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_SaveIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).SaveIndex(ctx, req.(*SaveIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_BatchSaveIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSaveIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).BatchSaveIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_BatchSaveIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).BatchSaveIndex(ctx, req.(*BatchSaveIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_DeleteByChunkIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByChunkIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).DeleteByChunkIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_DeleteByChunkIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).DeleteByChunkIDs(ctx, req.(*DeleteByChunkIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_DeleteBySourceIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBySourceIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).DeleteBySourceIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_DeleteBySourceIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).DeleteBySourceIDs(ctx, req.(*DeleteBySourceIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_DeleteByKnowledgeIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteByKnowledgeIDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).DeleteByKnowledgeIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_DeleteByKnowledgeIDs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).DeleteByKnowledgeIDs(ctx, req.(*DeleteByKnowledgeIDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_CopyIndices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyIndicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).CopyIndices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_CopyIndices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).CopyIndices(ctx, req.(*CopyIndicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_UpdateChunkEnabledStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChunkEnabledStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).UpdateChunkEnabledStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_UpdateChunkEnabledStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).UpdateChunkEnabledStatus(ctx, req.(*UpdateChunkEnabledStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RetrieverPlugin_UpdateChunkTagID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChunkTagIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrieverPluginServer).UpdateChunkTagID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RetrieverPlugin_UpdateChunkTagID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrieverPluginServer).UpdateChunkTagID(ctx, req.(*UpdateChunkTagIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RetrieverPlugin_ServiceDesc is the grpc.ServiceDesc for RetrieverPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RetrieverPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.RetrieverPlugin",
	HandlerType: (*RetrieverPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Describe",
			Handler:    _RetrieverPlugin_Describe_Handler,
		},
		{
			MethodName: "Retrieve",
			Handler:    _RetrieverPlugin_Retrieve_Handler,
		},
		{
			MethodName: "SaveIndex",
			Handler:    _RetrieverPlugin_SaveIndex_Handler,
		},
		{
			MethodName: "BatchSaveIndex",
			Handler:    _RetrieverPlugin_BatchSaveIndex_Handler,
		},
		{
			MethodName: "DeleteByChunkIDs",
			Handler:    _RetrieverPlugin_DeleteByChunkIDs_Handler,
		},
		{
			MethodName: "DeleteBySourceIDs",
			Handler:    _RetrieverPlugin_DeleteBySourceIDs_Handler,
		},
		{
			MethodName: "DeleteByKnowledgeIDs",
			Handler:    _RetrieverPlugin_DeleteByKnowledgeIDs_Handler,
		},
		{
			MethodName: "CopyIndices",
			Handler:    _RetrieverPlugin_CopyIndices_Handler,
		},
		{
			MethodName: "UpdateChunkEnabledStatus",
			Handler:    _RetrieverPlugin_UpdateChunkEnabledStatus_Handler,
		},
		{
			MethodName: "UpdateChunkTagID",
			Handler:    _RetrieverPlugin_UpdateChunkTagID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sdk/plugin/proto/plugin.proto",
}

const (
	DataSourcePlugin_ValidateCredentials_FullMethodName      = "/weknora.plugin.v1.DataSourcePlugin/ValidateCredentials"
	DataSourcePlugin_ListResources_FullMethodName            = "/weknora.plugin.v1.DataSourcePlugin/ListResources"
	DataSourcePlugin_ResolveResourceAncestors_FullMethodName = "/weknora.plugin.v1.DataSourcePlugin/ResolveResourceAncestors"
	DataSourcePlugin_FetchAll_FullMethodName                 = "/weknora.plugin.v1.DataSourcePlugin/FetchAll"
	DataSourcePlugin_Sync_FullMethodName                     = "/weknora.plugin.v1.DataSourcePlugin/Sync"
)

// DataSourcePluginClient is the client API for DataSourcePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataSourcePluginClient interface {
	ValidateCredentials(ctx context.Context, in *ValidateCredentialsRequest, opts ...grpc.CallOption) (*ValidateCredentialsResponse, error)
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	ResolveResourceAncestors(ctx context.Context, in *ResolveResourceAncestorsRequest, opts ...grpc.CallOption) (*ResolveResourceAncestorsResponse, error)
	FetchAll(ctx context.Context, in *FetchAllRequest, opts ...grpc.CallOption) (*FetchAllResponse, error)
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEvent], error)
}

type dataSourcePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewDataSourcePluginClient(cc grpc.ClientConnInterface) DataSourcePluginClient {
	return &dataSourcePluginClient{cc}
}

func (c *dataSourcePluginClient) ValidateCredentials(ctx context.Context, in *ValidateCredentialsRequest, opts ...grpc.CallOption) (*ValidateCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCredentialsResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ValidateCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) ResolveResourceAncestors(ctx context.Context, in *ResolveResourceAncestorsRequest, opts ...grpc.CallOption) (*ResolveResourceAncestorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResourceAncestorsResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_ResolveResourceAncestors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) FetchAll(ctx context.Context, in *FetchAllRequest, opts ...grpc.CallOption) (*FetchAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchAllResponse)
	err := c.cc.Invoke(ctx, DataSourcePlugin_FetchAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataSourcePluginClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DataSourcePlugin_ServiceDesc.Streams[0], DataSourcePlugin_Sync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SyncRequest, SyncEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SyncClient = grpc.ServerStreamingClient[SyncEvent]

// DataSourcePluginServer is the server API for DataSourcePlugin service.
// All implementations must embed UnimplementedDataSourcePluginServer
// for forward compatibility.
type DataSourcePluginServer interface {
	ValidateCredentials(context.Context, *ValidateCredentialsRequest) (*ValidateCredentialsResponse, error)
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest) (*ResolveResourceAncestorsResponse, error)
	FetchAll(context.Context, *FetchAllRequest) (*FetchAllResponse, error)
	Sync(*SyncRequest, grpc.ServerStreamingServer[SyncEvent]) error
	mustEmbedUnimplementedDataSourcePluginServer()
}

// UnimplementedDataSourcePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataSourcePluginServer struct{}

func (UnimplementedDataSourcePluginServer) ValidateCredentials(context.Context, *ValidateCredentialsRequest) (*ValidateCredentialsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateCredentials not implemented")
}
func (UnimplementedDataSourcePluginServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedDataSourcePluginServer) ResolveResourceAncestors(context.Context, *ResolveResourceAncestorsRequest) (*ResolveResourceAncestorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveResourceAncestors not implemented")
}
func (UnimplementedDataSourcePluginServer) FetchAll(context.Context, *FetchAllRequest) (*FetchAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchAll not implemented")
}
func (UnimplementedDataSourcePluginServer) Sync(*SyncRequest, grpc.ServerStreamingServer[SyncEvent]) error {
	return status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedDataSourcePluginServer) mustEmbedUnimplementedDataSourcePluginServer() {}
func (UnimplementedDataSourcePluginServer) testEmbeddedByValue()                          {}

// UnsafeDataSourcePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataSourcePluginServer will
// result in compilation errors.
type UnsafeDataSourcePluginServer interface {
	mustEmbedUnimplementedDataSourcePluginServer()
}

func RegisterDataSourcePluginServer(s grpc.ServiceRegistrar, srv DataSourcePluginServer) {
	// If the following call panics, it indicates UnimplementedDataSourcePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataSourcePlugin_ServiceDesc, srv)
}

func _DataSourcePlugin_ValidateCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ValidateCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ValidateCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ValidateCredentials(ctx, req.(*ValidateCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_ResolveResourceAncestors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveResourceAncestorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).ResolveResourceAncestors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_ResolveResourceAncestors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).ResolveResourceAncestors(ctx, req.(*ResolveResourceAncestorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_FetchAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataSourcePluginServer).FetchAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataSourcePlugin_FetchAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataSourcePluginServer).FetchAll(ctx, req.(*FetchAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataSourcePlugin_Sync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DataSourcePluginServer).Sync(m, &grpc.GenericServerStream[SyncRequest, SyncEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DataSourcePlugin_SyncServer = grpc.ServerStreamingServer[SyncEvent]

// DataSourcePlugin_ServiceDesc is the grpc.ServiceDesc for DataSourcePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataSourcePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "weknora.plugin.v1.DataSourcePlugin",
	HandlerType: (*DataSourcePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateCredentials",
			Handler:    _DataSourcePlugin_ValidateCredentials_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _DataSourcePlugin_ListResources_Handler,
		},
		{
			MethodName: "ResolveResourceAncestors",
			Handler:    _DataSourcePlugin_ResolveResourceAncestors_Handler,
		},
		{
			MethodName: "FetchAll",
			Handler:    _DataSourcePlugin_FetchAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Sync",
			Handler:       _DataSourcePlugin_Sync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "sdk/plugin/proto/plugin.proto",
}
