package main

import (
	"fmt"
	"path/filepath"
	"strings"
	"text/template"
)

// manifestTemplate renders a minimal but valid plugin.yaml for the given
// extension type. Capabilities are seeded to the empty set; authors add them
// as they implement features (e.g. document_parser gains "stream" when
// ParseStream is wired up).
//
// Network is enabled because the host rejects network-disabled process
// plugins (isolation is only enforceable under a container runtime). Plugins
// that must be offline ship a plugin.container.yaml instead — see the
// document-parser-plugin example.
func manifestTemplate(a scaffoldArgs) string {
	return fmt.Sprintf(`apiVersion: weknora.plugin/v1
kind: Plugin
metadata:
  id: %s
  name: %s
  version: 0.1.0
  description: TODO — replace with a short description of what this %s plugin does.
spec:
  extensionType: %s
  weknoraVersion: ">=0.1.0"
  capabilities: []
  entrypoint:
    type: process
    command: ["./%s"]
    grpcAddress: "%s"
  permissions:
    network:
      enabled: true
    filesystem: {}
  healthCheck:
    intervalSeconds: 30
    timeoutSeconds: 10
  restartPolicy:
    enabled: true
    maxAttempts: 3
    windowSeconds: 300
    backoffMillis: 5000
  configSchema:
    type: object
    properties: {}
`, a.ID, humanise(a.BinName), a.Type, a.Type, a.BinName, a.GRPCAddr)
}

// mainTemplate renders a runnable main.go implementing the extension service
// with Describe populated from the manifest and business RPCs returning
// Unimplemented so the plugin boots and passes the lifecycle half of the
// contract test before the author writes any real logic.
func mainTemplate(a scaffoldArgs) string {
	data := map[string]string{
		"ID":           a.ID,
		"Extension":    a.Type,
		"Registrar":    registrarCall(a.Type),
		"ServerStruct": serverStructTemplate(a.Type, humanise(a.BinName)),
	}
	tpl := template.Must(template.New("main").Parse(mainGoTemplate))
	var sb strings.Builder
	if err := tpl.Execute(&sb, data); err != nil {
		panic(err)
	}
	return sb.String()
}

const mainGoTemplate = `// Code generated by weknora-plugin init. Edit freely.
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"

	pluginpb "github.com/Tencent/WeKnora/sdk/plugin/proto"
	pluginsdk "github.com/Tencent/WeKnora/sdk/plugin/server"
)

const (
	pluginID      = "{{.ID}}"
	pluginVersion = "0.1.0"
)

{{.ServerStruct}}

func main() {
	s := &server{}
	s.Metadata = pluginsdk.Metadata{
		ID:             pluginID,
		Version:        pluginVersion,
		ExtensionTypes: []string{"{{.Extension}}"},
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()

	if err := pluginsdk.ServeContext(ctx, s, pluginsdk.Options{
		Address: pluginsdk.Address(),
	}, {{.Registrar}}); err != nil {
		os.Exit(1)
	}
}
`

// serverStructTemplate returns the server struct + Describe + Unimplemented
// business RPC stubs for the given extension type. displayName seeds the
// human-readable name returned by Describe.
func serverStructTemplate(extType, displayName string) string {
	switch extType {
	case "datasource":
		return fmt.Sprintf(`type server struct {
	pluginsdk.Lifecycle
	pluginpb.UnimplementedDataSourcePluginServer
}

func (s *server) ValidateCredentials(context.Context, *pluginpb.ValidateCredentialsRequest) (*pluginpb.ValidateCredentialsResponse, error) {
	return &pluginpb.ValidateCredentialsResponse{Valid: true}, nil
}

func (s *server) ListResources(context.Context, *pluginpb.ListResourcesRequest) (*pluginpb.ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement ListResources")
}

func (s *server) ResolveResourceAncestors(context.Context, *pluginpb.ResolveResourceAncestorsRequest) (*pluginpb.ResolveResourceAncestorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement ResolveResourceAncestors")
}

func (s *server) FetchAll(context.Context, *pluginpb.FetchAllRequest) (*pluginpb.FetchAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement FetchAll")
}

func (s *server) Sync(*pluginpb.SyncRequest, pluginpb.DataSourcePlugin_SyncServer) error {
	return status.Error(codes.Unimplemented, "implement Sync")
}

// describeName is the connector name the host registers this datasource under.
const describeName = %q`, displayName)
	case "document_parser":
		return fmt.Sprintf(`type server struct {
	pluginsdk.Lifecycle
	pluginpb.UnimplementedDocumentParserPluginServer
}

func (s *server) Describe(context.Context, *pluginpb.DocumentParserDescribeRequest) (*pluginpb.DocumentParserDescribeResponse, error) {
	return &pluginpb.DocumentParserDescribeResponse{
		EngineName:  %q,
		Description: "TODO — describe this parser",
		FileTypes:   []string{"md", "txt"},
	}, nil
}

func (s *server) Parse(context.Context, *pluginpb.DocumentParserParseRequest) (*pluginpb.DocumentParserParseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement Parse")
}

func (s *server) ParseStream(pluginpb.DocumentParserPlugin_ParseStreamServer) error {
	return status.Error(codes.Unimplemented, "implement ParseStream")
}`, displayName)
	case "web_search":
		return fmt.Sprintf(`type server struct {
	pluginsdk.Lifecycle
	pluginpb.UnimplementedWebSearchPluginServer
}

func (s *server) Describe(context.Context, *pluginpb.WebSearchDescribeRequest) (*pluginpb.WebSearchDescribeResponse, error) {
	return &pluginpb.WebSearchDescribeResponse{
		ProviderType: %q,
		DisplayName:  %q,
		Description:  "TODO — describe this search provider",
	}, nil
}

func (s *server) Search(context.Context, *pluginpb.WebSearchRequest) (*pluginpb.WebSearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement Search")
}`, displayName, displayName)
	case "model_provider":
		return fmt.Sprintf(`type server struct {
	pluginsdk.Lifecycle
	pluginpb.UnimplementedModelProviderPluginServer
}

func (s *server) Describe(context.Context, *pluginpb.ModelProviderDescribeRequest) (*pluginpb.ModelProviderDescribeResponse, error) {
	return &pluginpb.ModelProviderDescribeResponse{
		ProviderType: %q,
		DisplayName:  %q,
		Description:  "TODO — describe this model provider",
		ModelTypes:   []string{"chat"},
	}, nil
}

func (s *server) ListModels(context.Context, *pluginpb.ListModelsRequest) (*pluginpb.ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement ListModels")
}

func (s *server) Chat(*pluginpb.ChatRequest, pluginpb.ModelProviderPlugin_ChatServer) error {
	return status.Error(codes.Unimplemented, "implement Chat")
}

func (s *server) Embed(context.Context, *pluginpb.EmbedRequest) (*pluginpb.EmbedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement Embed")
}

func (s *server) Rerank(context.Context, *pluginpb.RerankRequest) (*pluginpb.RerankResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement Rerank")
}`, displayName, displayName)
	case "retriever":
		return fmt.Sprintf(`type server struct {
	pluginsdk.Lifecycle
	pluginpb.UnimplementedRetrieverPluginServer
}

func (s *server) Describe(context.Context, *pluginpb.RetrieverDescribeRequest) (*pluginpb.RetrieverDescribeResponse, error) {
	return &pluginpb.RetrieverDescribeResponse{
		EngineType:      %q,
		Description:     "TODO — describe this retriever",
		RetrieverTypes: []string{"vector"},
	}, nil
}

func (s *server) Retrieve(context.Context, *pluginpb.RetrieveRequest) (*pluginpb.RetrieveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement Retrieve")
}

func (s *server) SaveIndex(context.Context, *pluginpb.SaveIndexRequest) (*pluginpb.SaveIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement SaveIndex")
}

func (s *server) BatchSaveIndex(context.Context, *pluginpb.BatchSaveIndexRequest) (*pluginpb.BatchSaveIndexResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement BatchSaveIndex")
}

func (s *server) DeleteByChunkIDs(context.Context, *pluginpb.DeleteByChunkIDsRequest) (*pluginpb.DeleteByChunkIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement DeleteByChunkIDs")
}

func (s *server) DeleteBySourceIDs(context.Context, *pluginpb.DeleteBySourceIDsRequest) (*pluginpb.DeleteBySourceIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement DeleteBySourceIDs")
}

func (s *server) DeleteByKnowledgeIDs(context.Context, *pluginpb.DeleteByKnowledgeIDsRequest) (*pluginpb.DeleteByKnowledgeIDsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement DeleteByKnowledgeIDs")
}

func (s *server) CopyIndices(context.Context, *pluginpb.CopyIndicesRequest) (*pluginpb.CopyIndicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement CopyIndices")
}

func (s *server) UpdateChunkEnabledStatus(context.Context, *pluginpb.UpdateChunkEnabledStatusRequest) (*pluginpb.UpdateChunkEnabledStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement UpdateChunkEnabledStatus")
}

func (s *server) UpdateChunkTagID(context.Context, *pluginpb.UpdateChunkTagIDRequest) (*pluginpb.UpdateChunkTagIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "implement UpdateChunkTagID")
}`, displayName)
	}
	return ""
}

// registrarCall returns the literal SDK registrar invocation for the type.
func registrarCall(extType string) string {
	switch extType {
	case "datasource":
		return "pluginsdk.DataSourceService(s)"
	case "document_parser":
		return "pluginsdk.DocumentParserService(s)"
	case "web_search":
		return "pluginsdk.WebSearchService(s)"
	case "model_provider":
		return "pluginsdk.ModelProviderService(s)"
	case "retriever":
		return "pluginsdk.RetrieverService(s)"
	default:
		return "nil"
	}
}

func goModTemplate(a scaffoldArgs) string {
	base := fmt.Sprintf(`module %s

go 1.26.0

require github.com/Tencent/WeKnora/sdk/plugin v0.0.0-00010101000000-000000000000
`, a.Module)
	if a.SDKPath == "" {
		// No local checkout: rely on the published module once tagged.
		return base
	}
	// Local development: replace points at the caller's WeKnora checkout.
	// Quoted so paths with spaces parse correctly.
	return base + fmt.Sprintf(`
// Local development: points at a WeKnora checkout. Delete this replace and
// `+"`go get`"+` the published version before publishing the plugin.
replace github.com/Tencent/WeKnora/sdk/plugin => %q
`, filepath.ToSlash(a.SDKPath))
}

func readmeTemplate(a scaffoldArgs) string {
	return fmt.Sprintf(`# %s

A WeKnora %s plugin scaffolded by `+"`weknora-plugin init`"+`.

## Build

`+"```bash"+`
go mod tidy
go build
`+"```"+`

## Validate

`+"```bash"+`
weknora-plugin lint plugin.yaml
weknora-plugin test-contract .
`+"```"+`

## Install into WeKnora

Copy this directory under $WEKNORA_PLUGIN_DIR and restart the host:

`+"```bash"+`
cp -r . $WEKNORA_PLUGIN_DIR/%s
`+"```"+`

## Implement

Edit main.go and replace the TODO Describe fields and Unimplemented RPC stubs.
`, humanise(a.BinName), a.Type, basename(a.ID))
}

// humanise turns a binary name like "my-cool-parser" into "My Cool Parser".
func humanise(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, " ")
}
