// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/plugin/proto/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncErrorCode int32

const (
	SyncErrorCode_SYNC_ERROR_CODE_UNSPECIFIED            SyncErrorCode = 0
	SyncErrorCode_SYNC_ERROR_CODE_SECURITY_POLICY_DENIED SyncErrorCode = 1
)

// Enum value maps for SyncErrorCode.
var (
	SyncErrorCode_name = map[int32]string{
		0: "SYNC_ERROR_CODE_UNSPECIFIED",
		1: "SYNC_ERROR_CODE_SECURITY_POLICY_DENIED",
	}
	SyncErrorCode_value = map[string]int32{
		"SYNC_ERROR_CODE_UNSPECIFIED":            0,
		"SYNC_ERROR_CODE_SECURITY_POLICY_DENIED": 1,
	}
)

func (x SyncErrorCode) Enum() *SyncErrorCode {
	p := new(SyncErrorCode)
	*p = x
	return p
}

func (x SyncErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SyncErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_plugin_proto_plugin_proto_enumTypes[0].Descriptor()
}

func (SyncErrorCode) Type() protoreflect.EnumType {
	return &file_internal_plugin_proto_plugin_proto_enumTypes[0]
}

func (x SyncErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SyncErrorCode.Descriptor instead.
func (SyncErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse_Status int32

const (
	HealthCheckResponse_STATUS_UNSPECIFIED HealthCheckResponse_Status = 0
	HealthCheckResponse_STATUS_SERVING     HealthCheckResponse_Status = 1
	HealthCheckResponse_STATUS_NOT_SERVING HealthCheckResponse_Status = 2
)

// Enum value maps for HealthCheckResponse_Status.
var (
	HealthCheckResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_SERVING",
		2: "STATUS_NOT_SERVING",
	}
	HealthCheckResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_SERVING":     1,
		"STATUS_NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_Status) Enum() *HealthCheckResponse_Status {
	p := new(HealthCheckResponse_Status)
	*p = x
	return p
}

func (x HealthCheckResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_plugin_proto_plugin_proto_enumTypes[1].Descriptor()
}

func (HealthCheckResponse_Status) Type() protoreflect.EnumType {
	return &file_internal_plugin_proto_plugin_proto_enumTypes[1]
}

func (x HealthCheckResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_Status.Descriptor instead.
func (HealthCheckResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{3, 0}
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

type PluginInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version        string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	ExtensionTypes []string               `protobuf:"bytes,3,rep,name=extension_types,json=extensionTypes,proto3" json:"extension_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetExtensionTypes() []string {
	if x != nil {
		return x.ExtensionTypes
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Status        HealthCheckResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=weknora.plugin.v1.HealthCheckResponse_Status" json:"status,omitempty"`
	Message       string                     `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_Status {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_STATUS_UNSPECIFIED
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ValidateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigRequest.ProtoReflect.Descriptor instead.
func (*ValidateConfigRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ValidateConfigRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors        []*FieldError          `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateConfigResponse) Reset() {
	*x = ValidateConfigResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigResponse) ProtoMessage() {}

func (x *ValidateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateConfigResponse.ProtoReflect.Descriptor instead.
func (*ValidateConfigResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateConfigResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateConfigResponse) GetErrors() []*FieldError {
	if x != nil {
		return x.Errors
	}
	return nil
}

type FieldError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldError) Reset() {
	*x = FieldError{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldError) ProtoMessage() {}

func (x *FieldError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldError.ProtoReflect.Descriptor instead.
func (*FieldError) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *FieldError) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *FieldError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

type ValidateCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialsRequest) Reset() {
	*x = ValidateCredentialsRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialsRequest) ProtoMessage() {}

func (x *ValidateCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ValidateCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateCredentialsRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type ValidateCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCredentialsResponse) Reset() {
	*x = ValidateCredentialsResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCredentialsResponse) ProtoMessage() {}

func (x *ValidateCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ValidateCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateCredentialsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateCredentialsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListResourcesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesRequest) Reset() {
	*x = ListResourcesRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesRequest) ProtoMessage() {}

func (x *ListResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesRequest.ProtoReflect.Descriptor instead.
func (*ListResourcesRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ListResourcesRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ListResourcesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListResourcesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resources     []*Resource            `protobuf:"bytes,1,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResourcesResponse) Reset() {
	*x = ListResourcesResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResourcesResponse) ProtoMessage() {}

func (x *ListResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResourcesResponse.ProtoReflect.Descriptor instead.
func (*ListResourcesResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *ListResourcesResponse) GetResources() []*Resource {
	if x != nil {
		return x.Resources
	}
	return nil
}

type ResolveResourceAncestorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        map[string]string      `protobuf:"bytes,1,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceIds   []string               `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResourceAncestorsRequest) Reset() {
	*x = ResolveResourceAncestorsRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResourceAncestorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResourceAncestorsRequest) ProtoMessage() {}

func (x *ResolveResourceAncestorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResourceAncestorsRequest.ProtoReflect.Descriptor instead.
func (*ResolveResourceAncestorsRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveResourceAncestorsRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *ResolveResourceAncestorsRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type ResolveResourceAncestorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AncestorIds   []string               `protobuf:"bytes,1,rep,name=ancestor_ids,json=ancestorIds,proto3" json:"ancestor_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResourceAncestorsResponse) Reset() {
	*x = ResolveResourceAncestorsResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResourceAncestorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResourceAncestorsResponse) ProtoMessage() {}

func (x *ResolveResourceAncestorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResourceAncestorsResponse.ProtoReflect.Descriptor instead.
func (*ResolveResourceAncestorsResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveResourceAncestorsResponse) GetAncestorIds() []string {
	if x != nil {
		return x.AncestorIds
	}
	return nil
}

type FetchAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasourceId  string                 `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceIds   []string               `protobuf:"bytes,3,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAllRequest) Reset() {
	*x = FetchAllRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllRequest) ProtoMessage() {}

func (x *FetchAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllRequest.ProtoReflect.Descriptor instead.
func (*FetchAllRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *FetchAllRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *FetchAllRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *FetchAllRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type FetchAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Documents     []*Document            `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchAllResponse) Reset() {
	*x = FetchAllResponse{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchAllResponse) ProtoMessage() {}

func (x *FetchAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchAllResponse.ProtoReflect.Descriptor instead.
func (*FetchAllResponse) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{16}
}

func (x *FetchAllResponse) GetDocuments() []*Document {
	if x != nil {
		return x.Documents
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExternalId    string                 `protobuf:"bytes,1,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Url           string                 `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	ModifiedAt    string                 `protobuf:"bytes,6,opt,name=modified_at,json=modifiedAt,proto3" json:"modified_at,omitempty"`
	ParentId      string                 `protobuf:"bytes,7,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	HasChildren   bool                   `protobuf:"varint,8,opt,name=has_children,json=hasChildren,proto3" json:"has_children,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{17}
}

func (x *Resource) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Resource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Resource) GetModifiedAt() string {
	if x != nil {
		return x.ModifiedAt
	}
	return ""
}

func (x *Resource) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Resource) GetHasChildren() bool {
	if x != nil {
		return x.HasChildren
	}
	return false
}

func (x *Resource) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Document struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SourceId         string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceResourceId string                 `protobuf:"bytes,2,opt,name=source_resource_id,json=sourceResourceId,proto3" json:"source_resource_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Content          []byte                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	ContentType      string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Url              string                 `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Metadata         map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsDeleted        bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{18}
}

func (x *Document) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Document) GetSourceResourceId() string {
	if x != nil {
		return x.SourceResourceId
	}
	return ""
}

func (x *Document) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Document) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Document) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Document) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Document) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Document) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Document) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasourceId  string                 `protobuf:"bytes,1,opt,name=datasource_id,json=datasourceId,proto3" json:"datasource_id,omitempty"`
	Config        map[string]string      `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	ResourceIds   []string               `protobuf:"bytes,4,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{19}
}

func (x *SyncRequest) GetDatasourceId() string {
	if x != nil {
		return x.DatasourceId
	}
	return ""
}

func (x *SyncRequest) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SyncRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SyncRequest) GetResourceIds() []string {
	if x != nil {
		return x.ResourceIds
	}
	return nil
}

type SyncEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*SyncEvent_UpsertDocument
	//	*SyncEvent_DeleteDocument
	//	*SyncEvent_Progress
	//	*SyncEvent_Checkpoint
	//	*SyncEvent_Error
	//	*SyncEvent_Completed
	Payload       isSyncEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEvent) Reset() {
	*x = SyncEvent{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEvent) ProtoMessage() {}

func (x *SyncEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEvent.ProtoReflect.Descriptor instead.
func (*SyncEvent) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{20}
}

func (x *SyncEvent) GetPayload() isSyncEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SyncEvent) GetUpsertDocument() *UpsertDocument {
	if x != nil {
		if x, ok := x.Payload.(*SyncEvent_UpsertDocument); ok {
			return x.UpsertDocument
		}
	}
	return nil
}

func (x *SyncEvent) GetDeleteDocument() *DeleteDocument {
	if x != nil {
		if x, ok := x.Payload.(*SyncEvent_DeleteDocument); ok {
			return x.DeleteDocument
		}
	}
	return nil
}

func (x *SyncEvent) GetProgress() *Progress {
	if x != nil {
		if x, ok := x.Payload.(*SyncEvent_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *SyncEvent) GetCheckpoint() *Checkpoint {
	if x != nil {
		if x, ok := x.Payload.(*SyncEvent_Checkpoint); ok {
			return x.Checkpoint
		}
	}
	return nil
}

func (x *SyncEvent) GetError() *SyncError {
	if x != nil {
		if x, ok := x.Payload.(*SyncEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *SyncEvent) GetCompleted() *Completed {
	if x != nil {
		if x, ok := x.Payload.(*SyncEvent_Completed); ok {
			return x.Completed
		}
	}
	return nil
}

type isSyncEvent_Payload interface {
	isSyncEvent_Payload()
}

type SyncEvent_UpsertDocument struct {
	UpsertDocument *UpsertDocument `protobuf:"bytes,1,opt,name=upsert_document,json=upsertDocument,proto3,oneof"`
}

type SyncEvent_DeleteDocument struct {
	DeleteDocument *DeleteDocument `protobuf:"bytes,2,opt,name=delete_document,json=deleteDocument,proto3,oneof"`
}

type SyncEvent_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type SyncEvent_Checkpoint struct {
	Checkpoint *Checkpoint `protobuf:"bytes,4,opt,name=checkpoint,proto3,oneof"`
}

type SyncEvent_Error struct {
	Error *SyncError `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type SyncEvent_Completed struct {
	Completed *Completed `protobuf:"bytes,6,opt,name=completed,proto3,oneof"`
}

func (*SyncEvent_UpsertDocument) isSyncEvent_Payload() {}

func (*SyncEvent_DeleteDocument) isSyncEvent_Payload() {}

func (*SyncEvent_Progress) isSyncEvent_Payload() {}

func (*SyncEvent_Checkpoint) isSyncEvent_Payload() {}

func (*SyncEvent_Error) isSyncEvent_Payload() {}

func (*SyncEvent_Completed) isSyncEvent_Payload() {}

type UpsertDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Content       []byte                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UpdatedAt     string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertDocument) Reset() {
	*x = UpsertDocument{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDocument) ProtoMessage() {}

func (x *UpsertDocument) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDocument.ProtoReflect.Descriptor instead.
func (*UpsertDocument) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{21}
}

func (x *UpsertDocument) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *UpsertDocument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpsertDocument) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *UpsertDocument) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UpsertDocument) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpsertDocument) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type DeleteDocument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDocument) Reset() {
	*x = DeleteDocument{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDocument) ProtoMessage() {}

func (x *DeleteDocument) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDocument.ProtoReflect.Descriptor instead.
func (*DeleteDocument) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteDocument) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

type Progress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     uint64                 `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Total         uint64                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Progress) Reset() {
	*x = Progress{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{23}
}

func (x *Progress) GetCompleted() uint64 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *Progress) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Progress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Checkpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Checkpoint) Reset() {
	*x = Checkpoint{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Checkpoint) ProtoMessage() {}

func (x *Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Checkpoint.ProtoReflect.Descriptor instead.
func (*Checkpoint) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{24}
}

func (x *Checkpoint) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SyncError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Retryable     bool                   `protobuf:"varint,3,opt,name=retryable,proto3" json:"retryable,omitempty"`
	Code          SyncErrorCode          `protobuf:"varint,4,opt,name=code,proto3,enum=weknora.plugin.v1.SyncErrorCode" json:"code,omitempty"`
	Target        string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncError) Reset() {
	*x = SyncError{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncError) ProtoMessage() {}

func (x *SyncError) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncError.ProtoReflect.Descriptor instead.
func (*SyncError) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{25}
}

func (x *SyncError) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SyncError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SyncError) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *SyncError) GetCode() SyncErrorCode {
	if x != nil {
		return x.Code
	}
	return SyncErrorCode_SYNC_ERROR_CODE_UNSPECIFIED
}

func (x *SyncError) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type Completed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Completed) Reset() {
	*x = Completed{}
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Completed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Completed) ProtoMessage() {}

func (x *Completed) ProtoReflect() protoreflect.Message {
	mi := &file_internal_plugin_proto_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Completed.ProtoReflect.Descriptor instead.
func (*Completed) Descriptor() ([]byte, []int) {
	return file_internal_plugin_proto_plugin_proto_rawDescGZIP(), []int{26}
}

func (x *Completed) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

var File_internal_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_internal_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\"internal/plugin/proto/plugin.proto\x12\x11weknora.plugin.v1\"\x10\n" +
	"\x0eGetInfoRequest\"_\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12'\n" +
	"\x0fextension_types\x18\x03 \x03(\tR\x0eextensionTypes\"\x14\n" +
	"\x12HealthCheckRequest\"\xc4\x01\n" +
	"\x13HealthCheckResponse\x12E\n" +
	"\x06status\x18\x01 \x01(\x0e2-.weknora.plugin.v1.HealthCheckResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"L\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_SERVING\x10\x01\x12\x16\n" +
	"\x12STATUS_NOT_SERVING\x10\x02\"\xa0\x01\n" +
	"\x15ValidateConfigRequest\x12L\n" +
	"\x06config\x18\x01 \x03(\v24.weknora.plugin.v1.ValidateConfigRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"e\n" +
	"\x16ValidateConfigResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x125\n" +
	"\x06errors\x18\x02 \x03(\v2\x1d.weknora.plugin.v1.FieldErrorR\x06errors\"<\n" +
	"\n" +
	"FieldError\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\xaa\x01\n" +
	"\x1aValidateCredentialsRequest\x12Q\n" +
	"\x06config\x18\x01 \x03(\v29.weknora.plugin.v1.ValidateCredentialsRequest.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x1bValidateCredentialsResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbb\x01\n" +
	"\x14ListResourcesRequest\x12K\n" +
	"\x06config\x18\x01 \x03(\v23.weknora.plugin.v1.ListResourcesRequest.ConfigEntryR\x06config\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"R\n" +
	"\x15ListResourcesResponse\x129\n" +
	"\tresources\x18\x01 \x03(\v2\x1b.weknora.plugin.v1.ResourceR\tresources\"\xd7\x01\n" +
	"\x1fResolveResourceAncestorsRequest\x12V\n" +
	"\x06config\x18\x01 \x03(\v2>.weknora.plugin.v1.ResolveResourceAncestorsRequest.ConfigEntryR\x06config\x12!\n" +
	"\fresource_ids\x18\x02 \x03(\tR\vresourceIds\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	" ResolveResourceAncestorsResponse\x12!\n" +
	"\fancestor_ids\x18\x01 \x03(\tR\vancestorIds\"\xdc\x01\n" +
	"\x0fFetchAllRequest\x12#\n" +
	"\rdatasource_id\x18\x01 \x01(\tR\fdatasourceId\x12F\n" +
	"\x06config\x18\x02 \x03(\v2..weknora.plugin.v1.FetchAllRequest.ConfigEntryR\x06config\x12!\n" +
	"\fresource_ids\x18\x03 \x03(\tR\vresourceIds\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x10FetchAllResponse\x129\n" +
	"\tdocuments\x18\x01 \x03(\v2\x1b.weknora.plugin.v1.DocumentR\tdocuments\"\xec\x02\n" +
	"\bResource\x12\x1f\n" +
	"\vexternal_id\x18\x01 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x10\n" +
	"\x03url\x18\x05 \x01(\tR\x03url\x12\x1f\n" +
	"\vmodified_at\x18\x06 \x01(\tR\n" +
	"modifiedAt\x12\x1b\n" +
	"\tparent_id\x18\a \x01(\tR\bparentId\x12!\n" +
	"\fhas_children\x18\b \x01(\bR\vhasChildren\x12E\n" +
	"\bmetadata\x18\t \x03(\v2).weknora.plugin.v1.Resource.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xfa\x02\n" +
	"\bDocument\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12,\n" +
	"\x12source_resource_id\x18\x02 \x01(\tR\x10sourceResourceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x04 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12E\n" +
	"\bmetadata\x18\b \x03(\v2).weknora.plugin.v1.Document.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xec\x01\n" +
	"\vSyncRequest\x12#\n" +
	"\rdatasource_id\x18\x01 \x01(\tR\fdatasourceId\x12B\n" +
	"\x06config\x18\x02 \x03(\v2*.weknora.plugin.v1.SyncRequest.ConfigEntryR\x06config\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12!\n" +
	"\fresource_ids\x18\x04 \x03(\tR\vresourceIds\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa2\x03\n" +
	"\tSyncEvent\x12L\n" +
	"\x0fupsert_document\x18\x01 \x01(\v2!.weknora.plugin.v1.UpsertDocumentH\x00R\x0eupsertDocument\x12L\n" +
	"\x0fdelete_document\x18\x02 \x01(\v2!.weknora.plugin.v1.DeleteDocumentH\x00R\x0edeleteDocument\x129\n" +
	"\bprogress\x18\x03 \x01(\v2\x1b.weknora.plugin.v1.ProgressH\x00R\bprogress\x12?\n" +
	"\n" +
	"checkpoint\x18\x04 \x01(\v2\x1d.weknora.plugin.v1.CheckpointH\x00R\n" +
	"checkpoint\x124\n" +
	"\x05error\x18\x05 \x01(\v2\x1c.weknora.plugin.v1.SyncErrorH\x00R\x05error\x12<\n" +
	"\tcompleted\x18\x06 \x01(\v2\x1c.weknora.plugin.v1.CompletedH\x00R\tcompletedB\t\n" +
	"\apayload\"\xa7\x02\n" +
	"\x0eUpsertDocument\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acontent\x18\x03 \x01(\fR\acontent\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12K\n" +
	"\bmetadata\x18\x05 \x03(\v2/.weknora.plugin.v1.UpsertDocument.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"-\n" +
	"\x0eDeleteDocument\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\"X\n" +
	"\bProgress\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\x04R\tcompleted\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"$\n" +
	"\n" +
	"Checkpoint\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"\xae\x01\n" +
	"\tSyncError\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\tretryable\x18\x03 \x01(\bR\tretryable\x124\n" +
	"\x04code\x18\x04 \x01(\x0e2 .weknora.plugin.v1.SyncErrorCodeR\x04code\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\"#\n" +
	"\tCompleted\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor*\\\n" +
	"\rSyncErrorCode\x12\x1f\n" +
	"\x1bSYNC_ERROR_CODE_UNSPECIFIED\x10\x00\x12*\n" +
	"&SYNC_ERROR_CODE_SECURITY_POLICY_DENIED\x10\x012\xf8\x02\n" +
	"\x0fPluginLifecycle\x12K\n" +
	"\aGetInfo\x12!.weknora.plugin.v1.GetInfoRequest\x1a\x1d.weknora.plugin.v1.PluginInfo\x12\\\n" +
	"\vHealthCheck\x12%.weknora.plugin.v1.HealthCheckRequest\x1a&.weknora.plugin.v1.HealthCheckResponse\x12e\n" +
	"\x0eValidateConfig\x12(.weknora.plugin.v1.ValidateConfigRequest\x1a).weknora.plugin.v1.ValidateConfigResponse\x12S\n" +
	"\bShutdown\x12\".weknora.plugin.v1.ShutdownRequest\x1a#.weknora.plugin.v1.ShutdownResponse2\x8f\x04\n" +
	"\x10DataSourcePlugin\x12t\n" +
	"\x13ValidateCredentials\x12-.weknora.plugin.v1.ValidateCredentialsRequest\x1a..weknora.plugin.v1.ValidateCredentialsResponse\x12b\n" +
	"\rListResources\x12'.weknora.plugin.v1.ListResourcesRequest\x1a(.weknora.plugin.v1.ListResourcesResponse\x12\x83\x01\n" +
	"\x18ResolveResourceAncestors\x122.weknora.plugin.v1.ResolveResourceAncestorsRequest\x1a3.weknora.plugin.v1.ResolveResourceAncestorsResponse\x12S\n" +
	"\bFetchAll\x12\".weknora.plugin.v1.FetchAllRequest\x1a#.weknora.plugin.v1.FetchAllResponse\x12F\n" +
	"\x04Sync\x12\x1e.weknora.plugin.v1.SyncRequest\x1a\x1c.weknora.plugin.v1.SyncEvent0\x01B2Z0github.com/Tencent/WeKnora/internal/plugin/protob\x06proto3"

var (
	file_internal_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_internal_plugin_proto_plugin_proto_rawDescData []byte
)

func file_internal_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_internal_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_internal_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_internal_plugin_proto_plugin_proto_rawDescData
}

var file_internal_plugin_proto_plugin_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_internal_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_internal_plugin_proto_plugin_proto_goTypes = []any{
	(SyncErrorCode)(0),                       // 0: weknora.plugin.v1.SyncErrorCode
	(HealthCheckResponse_Status)(0),          // 1: weknora.plugin.v1.HealthCheckResponse.Status
	(*GetInfoRequest)(nil),                   // 2: weknora.plugin.v1.GetInfoRequest
	(*PluginInfo)(nil),                       // 3: weknora.plugin.v1.PluginInfo
	(*HealthCheckRequest)(nil),               // 4: weknora.plugin.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),              // 5: weknora.plugin.v1.HealthCheckResponse
	(*ValidateConfigRequest)(nil),            // 6: weknora.plugin.v1.ValidateConfigRequest
	(*ValidateConfigResponse)(nil),           // 7: weknora.plugin.v1.ValidateConfigResponse
	(*FieldError)(nil),                       // 8: weknora.plugin.v1.FieldError
	(*ShutdownRequest)(nil),                  // 9: weknora.plugin.v1.ShutdownRequest
	(*ShutdownResponse)(nil),                 // 10: weknora.plugin.v1.ShutdownResponse
	(*ValidateCredentialsRequest)(nil),       // 11: weknora.plugin.v1.ValidateCredentialsRequest
	(*ValidateCredentialsResponse)(nil),      // 12: weknora.plugin.v1.ValidateCredentialsResponse
	(*ListResourcesRequest)(nil),             // 13: weknora.plugin.v1.ListResourcesRequest
	(*ListResourcesResponse)(nil),            // 14: weknora.plugin.v1.ListResourcesResponse
	(*ResolveResourceAncestorsRequest)(nil),  // 15: weknora.plugin.v1.ResolveResourceAncestorsRequest
	(*ResolveResourceAncestorsResponse)(nil), // 16: weknora.plugin.v1.ResolveResourceAncestorsResponse
	(*FetchAllRequest)(nil),                  // 17: weknora.plugin.v1.FetchAllRequest
	(*FetchAllResponse)(nil),                 // 18: weknora.plugin.v1.FetchAllResponse
	(*Resource)(nil),                         // 19: weknora.plugin.v1.Resource
	(*Document)(nil),                         // 20: weknora.plugin.v1.Document
	(*SyncRequest)(nil),                      // 21: weknora.plugin.v1.SyncRequest
	(*SyncEvent)(nil),                        // 22: weknora.plugin.v1.SyncEvent
	(*UpsertDocument)(nil),                   // 23: weknora.plugin.v1.UpsertDocument
	(*DeleteDocument)(nil),                   // 24: weknora.plugin.v1.DeleteDocument
	(*Progress)(nil),                         // 25: weknora.plugin.v1.Progress
	(*Checkpoint)(nil),                       // 26: weknora.plugin.v1.Checkpoint
	(*SyncError)(nil),                        // 27: weknora.plugin.v1.SyncError
	(*Completed)(nil),                        // 28: weknora.plugin.v1.Completed
	nil,                                      // 29: weknora.plugin.v1.ValidateConfigRequest.ConfigEntry
	nil,                                      // 30: weknora.plugin.v1.ValidateCredentialsRequest.ConfigEntry
	nil,                                      // 31: weknora.plugin.v1.ListResourcesRequest.ConfigEntry
	nil,                                      // 32: weknora.plugin.v1.ResolveResourceAncestorsRequest.ConfigEntry
	nil,                                      // 33: weknora.plugin.v1.FetchAllRequest.ConfigEntry
	nil,                                      // 34: weknora.plugin.v1.Resource.MetadataEntry
	nil,                                      // 35: weknora.plugin.v1.Document.MetadataEntry
	nil,                                      // 36: weknora.plugin.v1.SyncRequest.ConfigEntry
	nil,                                      // 37: weknora.plugin.v1.UpsertDocument.MetadataEntry
}
var file_internal_plugin_proto_plugin_proto_depIdxs = []int32{
	1,  // 0: weknora.plugin.v1.HealthCheckResponse.status:type_name -> weknora.plugin.v1.HealthCheckResponse.Status
	29, // 1: weknora.plugin.v1.ValidateConfigRequest.config:type_name -> weknora.plugin.v1.ValidateConfigRequest.ConfigEntry
	8,  // 2: weknora.plugin.v1.ValidateConfigResponse.errors:type_name -> weknora.plugin.v1.FieldError
	30, // 3: weknora.plugin.v1.ValidateCredentialsRequest.config:type_name -> weknora.plugin.v1.ValidateCredentialsRequest.ConfigEntry
	31, // 4: weknora.plugin.v1.ListResourcesRequest.config:type_name -> weknora.plugin.v1.ListResourcesRequest.ConfigEntry
	19, // 5: weknora.plugin.v1.ListResourcesResponse.resources:type_name -> weknora.plugin.v1.Resource
	32, // 6: weknora.plugin.v1.ResolveResourceAncestorsRequest.config:type_name -> weknora.plugin.v1.ResolveResourceAncestorsRequest.ConfigEntry
	33, // 7: weknora.plugin.v1.FetchAllRequest.config:type_name -> weknora.plugin.v1.FetchAllRequest.ConfigEntry
	20, // 8: weknora.plugin.v1.FetchAllResponse.documents:type_name -> weknora.plugin.v1.Document
	34, // 9: weknora.plugin.v1.Resource.metadata:type_name -> weknora.plugin.v1.Resource.MetadataEntry
	35, // 10: weknora.plugin.v1.Document.metadata:type_name -> weknora.plugin.v1.Document.MetadataEntry
	36, // 11: weknora.plugin.v1.SyncRequest.config:type_name -> weknora.plugin.v1.SyncRequest.ConfigEntry
	23, // 12: weknora.plugin.v1.SyncEvent.upsert_document:type_name -> weknora.plugin.v1.UpsertDocument
	24, // 13: weknora.plugin.v1.SyncEvent.delete_document:type_name -> weknora.plugin.v1.DeleteDocument
	25, // 14: weknora.plugin.v1.SyncEvent.progress:type_name -> weknora.plugin.v1.Progress
	26, // 15: weknora.plugin.v1.SyncEvent.checkpoint:type_name -> weknora.plugin.v1.Checkpoint
	27, // 16: weknora.plugin.v1.SyncEvent.error:type_name -> weknora.plugin.v1.SyncError
	28, // 17: weknora.plugin.v1.SyncEvent.completed:type_name -> weknora.plugin.v1.Completed
	37, // 18: weknora.plugin.v1.UpsertDocument.metadata:type_name -> weknora.plugin.v1.UpsertDocument.MetadataEntry
	0,  // 19: weknora.plugin.v1.SyncError.code:type_name -> weknora.plugin.v1.SyncErrorCode
	2,  // 20: weknora.plugin.v1.PluginLifecycle.GetInfo:input_type -> weknora.plugin.v1.GetInfoRequest
	4,  // 21: weknora.plugin.v1.PluginLifecycle.HealthCheck:input_type -> weknora.plugin.v1.HealthCheckRequest
	6,  // 22: weknora.plugin.v1.PluginLifecycle.ValidateConfig:input_type -> weknora.plugin.v1.ValidateConfigRequest
	9,  // 23: weknora.plugin.v1.PluginLifecycle.Shutdown:input_type -> weknora.plugin.v1.ShutdownRequest
	11, // 24: weknora.plugin.v1.DataSourcePlugin.ValidateCredentials:input_type -> weknora.plugin.v1.ValidateCredentialsRequest
	13, // 25: weknora.plugin.v1.DataSourcePlugin.ListResources:input_type -> weknora.plugin.v1.ListResourcesRequest
	15, // 26: weknora.plugin.v1.DataSourcePlugin.ResolveResourceAncestors:input_type -> weknora.plugin.v1.ResolveResourceAncestorsRequest
	17, // 27: weknora.plugin.v1.DataSourcePlugin.FetchAll:input_type -> weknora.plugin.v1.FetchAllRequest
	21, // 28: weknora.plugin.v1.DataSourcePlugin.Sync:input_type -> weknora.plugin.v1.SyncRequest
	3,  // 29: weknora.plugin.v1.PluginLifecycle.GetInfo:output_type -> weknora.plugin.v1.PluginInfo
	5,  // 30: weknora.plugin.v1.PluginLifecycle.HealthCheck:output_type -> weknora.plugin.v1.HealthCheckResponse
	7,  // 31: weknora.plugin.v1.PluginLifecycle.ValidateConfig:output_type -> weknora.plugin.v1.ValidateConfigResponse
	10, // 32: weknora.plugin.v1.PluginLifecycle.Shutdown:output_type -> weknora.plugin.v1.ShutdownResponse
	12, // 33: weknora.plugin.v1.DataSourcePlugin.ValidateCredentials:output_type -> weknora.plugin.v1.ValidateCredentialsResponse
	14, // 34: weknora.plugin.v1.DataSourcePlugin.ListResources:output_type -> weknora.plugin.v1.ListResourcesResponse
	16, // 35: weknora.plugin.v1.DataSourcePlugin.ResolveResourceAncestors:output_type -> weknora.plugin.v1.ResolveResourceAncestorsResponse
	18, // 36: weknora.plugin.v1.DataSourcePlugin.FetchAll:output_type -> weknora.plugin.v1.FetchAllResponse
	22, // 37: weknora.plugin.v1.DataSourcePlugin.Sync:output_type -> weknora.plugin.v1.SyncEvent
	29, // [29:38] is the sub-list for method output_type
	20, // [20:29] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_internal_plugin_proto_plugin_proto_init() }
func file_internal_plugin_proto_plugin_proto_init() {
	if File_internal_plugin_proto_plugin_proto != nil {
		return
	}
	file_internal_plugin_proto_plugin_proto_msgTypes[20].OneofWrappers = []any{
		(*SyncEvent_UpsertDocument)(nil),
		(*SyncEvent_DeleteDocument)(nil),
		(*SyncEvent_Progress)(nil),
		(*SyncEvent_Checkpoint)(nil),
		(*SyncEvent_Error)(nil),
		(*SyncEvent_Completed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_plugin_proto_plugin_proto_rawDesc), len(file_internal_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_internal_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_internal_plugin_proto_plugin_proto_depIdxs,
		EnumInfos:         file_internal_plugin_proto_plugin_proto_enumTypes,
		MessageInfos:      file_internal_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_internal_plugin_proto_plugin_proto = out.File
	file_internal_plugin_proto_plugin_proto_goTypes = nil
	file_internal_plugin_proto_plugin_proto_depIdxs = nil
}
